title: Renio's Blog
description: "Kong Eunho"
author: Renio
site_title: "Renio's Blog"
lang: ko-KR
timezone: Asia/Seoul
url: "https://devRenio.github.io"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: devRenio
blog_url: https://www.nagekar.com
email: eunho9684@naver.com
keybase_username: Renio
twitter_username: Renio
reddit_username: Renio

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:

plugins:
  - jekyll-sitemap
