title: devRenio
description: "Kong Eunho"
author: Renio
site_title: "devRenio"
lang: ko-KR
timezone: Asia/Seoul
url: "https://devRenio.github.io/"

paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

collections:
  blog:
    output: true
    permalink: /blog/:title/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor/ruby]

# Personalization
github_username: devRenio
blog_url: ""
email: eunho9684@naver.com
keybase_username: Renio
twitter_username: Renio
reddit_username: Renio

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:

plugins:
  - jekyll-sitemap
